version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            -"aa:91:85:0c:fe:27:a3:0c:75:46:91:55:21:26:78:27"

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: AWS EC2 Deploy
          command: |
            # delete existing files & create /tmp/server
            ssh -o StrictHostKeyChecking=no \
              ec2-user@${EC2_HOSTNAME} "rm -rf /tmp/server && mkdir /tmp/server" \
            # upload installation script
            scp -r -o StrictHostKeyChecking=no ./install-factorio-server.sh ./docker/docker-compose.yml \
              ec2-user@${EC2_HOSTNAME}:/tmp/server
            # run installation script in remote
            ssh -o StrictHostKeyChecking=no \
              ec2-user@${EC2_HOSTNAME} "sh /tmp/server/install-factorio-server.sh"