version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            -"11:9e:cf:5f:a9:d1:fc:43:a2:99:ff:f3:f0:9f:8c:37"

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: AWS EC2 Deploy
          command: |
            # upload installation script
            scp -r -o StrictHostKeyChecking=no ./install-factorio-server.sh \
              ec2-54-208-170-217.compute-1.amazonaws.com:/tmp
            # run installation script in remote
            ssh -o StrictHostKeyChecking=no \
              ec2-54-208-170-217.compute-1.amazonaws.com "/tmp/install-factorio-server.sh"
            