version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            -"11:9e:cf:5f:a9:d1:fc:43:a2:99:ff:f3:f0:9f:8c:37"

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: AWS EC2 Deploy
          command: |
            # delete existing files
            ssh -o StrictHostKeyChecking=no \
              ec2-user@ec2-3-89-238-22.compute-1.amazonaws.com "rm -rf /tmp/server"
            # create /tmp/server
            ssh -o StrictHostKeyChecking=no \
              ec2-user@ec2-3-89-238-22.compute-1.amazonaws.com "mkdir /tmp/server"
            # upload installation script
            scp -r -o StrictHostKeyChecking=no ./install-factorio-server.sh ./docker/docker-compose.yml \
              ec2-user@ec2-3-89-238-22.compute-1.amazonaws.com:/tmp/server
            # run installation script in remote
            ssh -o StrictHostKeyChecking=no \
              ec2-user@ec2-3-89-238-22.compute-1.amazonaws.com "sh /tmp/server/install-factorio-server.sh"
            