FROM centos:latest

LABEL maintainer="austin.dev@outlook.com"
LABEL description="A Factorio Server"
LABEL version="0.1"

ENV PORT=34197 \
	RCON_PORT=27015 \
	VERSION=0.16.51 \
	PUID=845 \
	PGID=845 \
	USER=factorio \
	GROUP=factorio \
	SAVES=/opt/factorio/s3/saves \
	CONFIG=/opt/factorio/s3/config \
	MODS=/opt/factorio/s3/mods \
	SCENARIOS=/opt/factorio/s3/scenarios

## update CentOS and clean
RUN yum -y -q -e 0 update && \
	yum -y -q -e 0 install curl gcc make && \
	curl -sSL "https://github.com/ncopa/su-exec/archive/v0.2.tar.gz" -o /tmp/su-exec.tar.gz && \
	tar xf "/tmp/su-exec.tar.gz" --directory /tmp && \
	rm /tmp/su-exec.tar.gz && \
	cd /tmp/su-exec-0.2 && \
	make && \
	mv su-exec /usr/local/bin && \
	PATH=$PATH:/usr/local/bin/su-exec && \
	cd / && \
	rm -rf /tmp/su-exec-0.2 && \
	yum clean all && \
	rm -rf /var/cache/yum

# download and setup factorio assets
RUN	curl -sSL "https://www.factorio.com/get-download/$VERSION/headless/linux64" \
	-o /tmp/factorio_headless_x64_$VERSION.tar.xz && \
	echo "downloaded /tmp/factorio_headless_x64_$VERSION.tar.xz" && \
	tar xf "/tmp/factorio_headless_x64_$VERSION.tar.xz" --directory /opt && \
	chmod ugo=rwx /opt/factorio && \
	rm "/tmp/factorio_headless_x64_$VERSION.tar.xz" && \
	mkdir -p /opt/factorio/s3 && \
	ln -s "$SAVES" /opt/factorio/saves && \
	ln -s "$CONFIG" /opt/factorio/config && \
	ln -s "$SCENARIOS" /opt/factorio/scenarios && \
	ln -s "$MODS" /opt/factorio/mods && \
	groupadd -g "$PGID" "$GROUP" && \
	useradd -u "$PUID" -g "$GROUP" --no-create-home -s /bin/sh "$USER" && \
	chown -R "$USER":"$GROUP" /opt/factorio /opt/factorio/s3

ADD /scripts/* /opt/factorio/scripts/

EXPOSE ${PORT}/udp ${RCON_PORT}/tcp

# ENTRYPOINT [ "/opt/factorio/scripts/start-server.sh" ]